import type { CustomerData } from './types';

export const sampleData: CustomerData = {
  slug: 'sample',
  company: 'サンプル不動産株式会社',
  licenseNo: '東京都知事(1)第00000号',
  lineUrl: 'https://line.me/R/ti/p/@sample000',
  tel: '03-0000-0000',
  logoUrl: '/f-media/sample/logo.png',
  catchCopy: '街の暮らしを動画で紹介する不動産会社です',
  tradeType: '仲介',
  address: {
    postalCode: '100-0001',
    prefecture: '東京都',
    city: '千代田区',
    streetAddress: 'サンプル1-1-1',
  },
  companyDescription:
    'サンプル不動産株式会社は地域の賃貸物件を動画でご紹介する仲介業者です。内見前に部屋の雰囲気が伝わる動画コンテンツを制作しています。',
  properties: [
    {
      id: 'sample-001',
      title: 'サンプルタウン駅前1LDK',
      area: '千代田区',
      address: '東京都千代田区サンプル1-2-3',
      rentMan: 12.8,
      managementFeeYen: 8000,
      depositMan: 12.8,
      keyMoneyMan: 12.8,
      layout: '1LDK',
      sizeSqm: 35.42,
      walkMin: 5,
      structure: 'RC造',
      availableFrom: '2026-08-01',
      videoUrl: '/f-media/sample/1.mp4',
      posterUrl: '/f-media/sample/1.jpg',
      status: 'active',
      tags: ['駅近', 'リノベーション', 'ペット相談'],
      description: '駅から徒歩5分の1LDKタイプです。室内は独立洗面台とバルコニーを備えています。',
      stationName: 'サンプル駅',
      floor: '3階',
      buildingAge: 12,
      order: 1,
      uploadDate: '2026-06-01T09:00:00+09:00',
      videoDurationSec: 42,
      aspect: '9:16',
    },
    {
      id: 'sample-002',
      title: 'サンプル公園通り2DK',
      area: '中央区',
      address: '東京都中央区サンプル4-5-6',
      rentMan: 15.5,
      managementFeeYen: 10000,
      depositMan: 15.5,
      keyMoneyMan: 0,
      layout: '2DK',
      sizeSqm: 42.1,
      walkMin: 8,
      structure: '鉄骨造',
      availableFrom: '2026-07-15',
      videoUrl: '/f-media/sample/2.mp4',
      posterUrl: '/f-media/sample/2.jpg',
      status: 'active',
      tags: ['公園近く', '収納充実'],
      description: '公園沿いの落ち着いた住環境にある2DKです。収納スペースが多く暮らしやすい設計です。',
      stationName: 'サンプル公園駅',
      floor: '2階',
      buildingAge: 20,
      order: 2,
      uploadDate: '2026-06-05T10:00:00+09:00',
      videoDurationSec: 38,
      aspect: '1:1',
    },
    {
      id: 'sample-003',
      title: 'サンプル河岸ビュー1K',
      area: '港区',
      address: '東京都港区サンプル7-8-9',
      rentMan: 9.8,
      managementFeeYen: 6000,
      depositMan: 9.8,
      keyMoneyMan: 9.8,
      layout: '1K',
      sizeSqm: 24.6,
      walkMin: 3,
      structure: 'RC造',
      availableFrom: '2026-08-10',
      videoUrl: '/f-media/sample/3.mp4',
      posterUrl: '/f-media/sample/3.jpg',
      status: 'active',
      tags: ['単身向け', 'オートロック'],
      description: '単身の方向けのコンパクトな1Kです。オートロック付きで防犯面も安心です。',
      stationName: 'サンプル河岸駅',
      floor: '5階',
      buildingAge: 8,
      order: 3,
      uploadDate: '2026-06-10T11:00:00+09:00',
      videoDurationSec: 35,
      aspect: '9:16',
    },
    {
      id: 'sample-004',
      title: 'サンプル丘上テラス3LDK',
      area: '目黒区',
      address: '東京都目黒区サンプル10-11-12',
      rentMan: 22,
      managementFeeYen: 12000,
      depositMan: 22,
      keyMoneyMan: 22,
      layout: '3LDK',
      sizeSqm: 68.3,
      walkMin: 12,
      structure: 'RC造',
      availableFrom: '2026-09-01',
      videoUrl: '/f-media/sample/4.mp4',
      posterUrl: '/f-media/sample/4.jpg',
      status: 'active',
      tags: ['ファミリー向け', 'テラス付き'],
      description: 'ファミリー向けの3LDKで、専用テラスがあります。周辺には学校や公園があります。',
      stationName: 'サンプル丘駅',
      floor: '1階',
      buildingAge: 15,
      order: 4,
      uploadDate: '2026-06-15T09:30:00+09:00',
      videoDurationSec: 55,
      aspect: '1:1',
    },
    {
      id: 'sample-005',
      title: 'サンプル新橋通り1R',
      area: '新宿区',
      address: '東京都新宿区サンプル13-14-15',
      rentMan: 7.9,
      managementFeeYen: 5000,
      depositMan: 7.9,
      keyMoneyMan: 0,
      layout: '1R',
      sizeSqm: 18.2,
      walkMin: 6,
      structure: '軽量鉄骨造',
      availableFrom: '2026-07-20',
      videoUrl: '/f-media/sample/5.mp4',
      posterUrl: '/f-media/sample/5.jpg',
      status: 'active',
      tags: ['駅近', '即入居可'],
      description: 'コンパクトな1Rタイプで、初めての一人暮らしにも適した設計です。',
      stationName: 'サンプル新橋駅',
      floor: '4階',
      buildingAge: 25,
      order: 5,
      uploadDate: '2026-06-20T13:00:00+09:00',
      videoDurationSec: 30,
      aspect: '9:16',
    },
    {
      id: 'sample-006',
      title: 'サンプル駅南1LDK',
      area: '渋谷区',
      address: '東京都渋谷区サンプル16-17-18',
      rentMan: 13.2,
      managementFeeYen: 8000,
      depositMan: 13.2,
      keyMoneyMan: 13.2,
      layout: '1LDK',
      sizeSqm: 33.5,
      walkMin: 7,
      structure: 'RC造',
      availableFrom: '2026-05-01',
      videoUrl: '/f-media/sample/6.mp4',
      posterUrl: '/f-media/sample/6.jpg',
      status: 'closed',
      tags: ['成約済み'],
      description: 'このお部屋は成約済みです。',
      stationName: 'サンプル駅',
      floor: '6階',
      buildingAge: 10,
      order: 6,
      uploadDate: '2026-05-25T09:00:00+09:00',
      videoDurationSec: 40,
    },
  ],
};
